const scenes=[...document.querySelectorAll('.scene')],revealButton=document.querySelector('#reveal-button'),celebrateAgainButton=document.querySelector('#celebrate-again'),countdownNumber=document.querySelector('#countdown-number'),canvas=document.querySelector('#confetti'),ctx=canvas.getContext('2d');let assignmentData=null,particles=[],animationFrame=null;
const base64UrlToBytes=value=>{const normalized=value.replace(/-/g,'+').replace(/_/g,'/'),padded=normalized+'='.repeat((4-normalized.length%4)%4);return Uint8Array.from(atob(padded),character=>character.charCodeAt(0))};
async function decryptAssignment(){const token=location.hash.slice(1);if(!token)return null;const[version,keyPart,ivPart,cipherPart]=token.split('.');if(version!=='v1'||!keyPart||!ivPart||!cipherPart)throw new Error('Invalid token');const key=await crypto.subtle.importKey('raw',base64UrlToBytes(keyPart),'AES-GCM',false,['decrypt']);const decrypted=await crypto.subtle.decrypt({name:'AES-GCM',iv:base64UrlToBytes(ivPart)},key,base64UrlToBytes(cipherPart));return JSON.parse(new TextDecoder().decode(decrypted))}
function normalizeAssignment(data){if(!data)return null;const area=data.t==='p'?'primaria':data.t==='m'?'media':data.area;return{name:data.n||data.name,assignment:data.a||data.assignment,area,welcome:data.welcome,message:data.message||(area==='primaria'?'Tu dedicación, creatividad y cariño harán de este grado un espacio lleno de aprendizajes, alegría y momentos inolvidables. ¡Confiamos en la hermosa huella que dejarás!':'Tu acompañamiento, compromiso y liderazgo serán fundamentales para orientar a tus estudiantes en esta nueva etapa. ¡Estamos seguros de que juntos vivirán un año extraordinario!')}}
function showScene(id){scenes.forEach(scene=>scene.classList.toggle('is-active',scene.id===id))}function populateWelcome(data){document.querySelector('#teacher-name').textContent=data.name;document.querySelector('#welcome-copy').textContent=data.welcome||'La familia COLMAGEPI ha preparado una misión muy especial para ti.'}
function populateResult(data){const isPrimary=data.area==='primaria';document.querySelector('#result-kind').textContent=isPrimary?'Tu grado para este año escolar':'Tu guiatura para este año escolar';document.querySelector('#result-title').textContent=isPrimary?'¡Una experiencia maravillosa te espera!':'¡Tu liderazgo inspirará una nueva etapa!';document.querySelector('#result-name').textContent=data.name;document.querySelector('#assignment-label').textContent=isPrimary?'Serás la docente de':'Serás docente guía de';document.querySelector('#assignment').textContent=data.assignment;document.querySelector('#result-message').textContent=data.message}
function playCelebrationSound(){try{const AudioContext=window.AudioContext||window.webkitAudioContext,audio=new AudioContext(),now=audio.currentTime;[523.25,659.25,783.99,1046.5].forEach((frequency,index)=>{const oscillator=audio.createOscillator(),gain=audio.createGain();oscillator.type='sine';oscillator.frequency.value=frequency;gain.gain.setValueAtTime(0,now+index*.13);gain.gain.linearRampToValueAtTime(.14,now+index*.13+.02);gain.gain.exponentialRampToValueAtTime(.001,now+index*.13+.42);oscillator.connect(gain).connect(audio.destination);oscillator.start(now+index*.13);oscillator.stop(now+index*.13+.45)})}catch(_){}}
function resizeCanvas(){const ratio=Math.min(window.devicePixelRatio||1,2);canvas.width=innerWidth*ratio;canvas.height=innerHeight*ratio;canvas.style.width=`${innerWidth}px`;canvas.style.height=`${innerHeight}px`;ctx.setTransform(ratio,0,0,ratio,0,0)}
function launchConfetti(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;cancelAnimationFrame(animationFrame);resizeCanvas();const colors=['#d8e928','#f4c94d','#ffffff','#19a45c','#ff7e67'];particles=Array.from({length:Math.min(170,Math.floor(innerWidth*.38))},()=>({x:innerWidth*.5+(Math.random()-.5)*120,y:innerHeight*.34,vx:(Math.random()-.5)*13,vy:-Math.random()*10-4,gravity:.18+Math.random()*.08,drag:.992,rotation:Math.random()*Math.PI,spin:(Math.random()-.5)*.25,size:5+Math.random()*7,color:colors[Math.floor(Math.random()*colors.length)],life:150+Math.random()*80}));const animate=()=>{ctx.clearRect(0,0,innerWidth,innerHeight);particles=particles.filter(particle=>particle.life>0&&particle.y<innerHeight+30);particles.forEach(particle=>{particle.vx*=particle.drag;particle.vy+=particle.gravity;particle.x+=particle.vx;particle.y+=particle.vy;particle.rotation+=particle.spin;particle.life-=1;ctx.save();ctx.translate(particle.x,particle.y);ctx.rotate(particle.rotation);ctx.fillStyle=particle.color;ctx.fillRect(-particle.size/2,-particle.size/3,particle.size,particle.size*.66);ctx.restore()});if(particles.length)animationFrame=requestAnimationFrame(animate);else ctx.clearRect(0,0,innerWidth,innerHeight)};animate()}
async function startReveal(){revealButton.disabled=true;showScene('countdown');playCelebrationSound();for(const number of['3','2','1']){countdownNumber.textContent=number;countdownNumber.style.animation='none';void countdownNumber.offsetWidth;countdownNumber.style.animation='';await new Promise(resolve=>setTimeout(resolve,820))}populateResult(assignmentData);showScene('result');launchConfetti();revealButton.disabled=false}
revealButton.addEventListener('click',startReveal);celebrateAgainButton.addEventListener('click',()=>{playCelebrationSound();launchConfetti()});window.addEventListener('resize',resizeCanvas,{passive:true});(async()=>{try{assignmentData=normalizeAssignment(await decryptAssignment());if(!assignmentData){showScene('empty');return}populateWelcome(assignmentData);showScene('welcome')}catch(_){showScene('error')}})();
